version: '3'

services:
    db:
        image: 'postgres:11'
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=test
            - POSTGRES_DB=test-db
